on:
  release:
    types: ['published']
jobs:
  build:
    runs-on: ${{ matrix.os.type }}
    strategy:
      fail-fast: false
      matrix:
        os: [{ type: 'ubuntu-20.04', binary: '' }, { type: 'macos-latest', binary: ''}, { type: 'windows-latest', binary: '.exe' }]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller tagstudio/tag_studio.py
    - uses: actions/upload-artifact@v4
      with:
        name: tagstudio-${{ maxtrix.os }}
        path: dist/tag_studio/tagstudio-${{ matrix.os.type }}${{ matrix.os.binary }}
